security:
    firewalls:
        pdv_firewall:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /check
                default_target_path:  /principal
                
            logout:
                path: /logout
                target: /index
                
    role_hierarchy:
        ROLE_OPERADOR:  [ROLE_USER, ROLE_OPERADOR]
        ROLE_ADMIN: [ROLE_ADMIN,ROLE_OPERADOR]
        
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /index, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /empresa/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /principal/, roles:[ROLE_ADMIN,ROLE_OPERADOR]}
        
    providers:
        pdv_providers:
           entity:  
               class: Multinet\PdvEnlinea\PdvEnlineaBundle\Entity\Empleado
               property: usuariosistema 
    encoders:
        Multinet\PdvEnlinea\PdvEnlineaBundle\Entity\Empleado: sha512