Cliente:
    type: entity
    table: cliente
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombrecliente:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: nombreCliente
        nitcliente:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: NitCliente
        direccioncliente:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: direccionCliente
        mailcliente:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: mailCliente
        status:
            type: boolean
            nullable: true
            default: '1'
        createdat:
            type: datetime
            nullable: false
            column: createdAt
        updatedat:
            type: datetime
            nullable: false
            column: updatedAt
    lifecycleCallbacks: {  }
