EmpresaResolucion:
    type: entity
    table: empresa_resolucion
    indexes:
        fk_empresaresolucion_empresa_idx:
            columns:
                - id_empresa
        fk_empresaresolucion_resolucion_idx:
            columns:
                - id_resolucion
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        status:
            type: boolean
            nullable: true
        createdAt:
            type: date
            nullable: true
            column: created_at
        updatedAt:
            type: date
            nullable: true
            column: updated_at
    manyToOne:
        idEmpresa:
            targetEntity: Empresa
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_empresa:
                    referencedColumnName: id
            orphanRemoval: false
        idResolucion:
            targetEntity: ResolucionSat
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_resolucion:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
