Fabricante:
    type: entity
    table: fabricante
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            fixed: false
        direccion:
            type: string
            nullable: false
            length: 255
            fixed: false
        telefono:
            type: string
            nullable: false
            length: 255
            fixed: false
        contacto:
            type: string
            nullable: false
            length: 255
            fixed: false
        status:
            type: boolean
            nullable: true
            default: '1'
        createdat:
            type: datetime
            nullable: false
            column: createdAt
        updatedat:
            type: datetime
            nullable: false
            column: updatedAt
    lifecycleCallbacks: {  }
