Factura:
    type: entity
    table: factura
    indexes:
        idEmpleado:
            columns:
                - idEmpleado
        fk_factura_sucursal_idx:
            columns:
                - id_sucursal
        fk_factura_cliente_idx:
            columns:
                - id_cliente
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        status:
            type: boolean
            nullable: true
            default: '1'
        createdat:
            type: datetime
            nullable: false
            column: createdAt
        updatedat:
            type: datetime
            nullable: false
            column: updatedAt
        fechaFactura:
            type: date
            nullable: true
            column: fecha_factura
        estadoCierre:
            type: boolean
            nullable: true
            column: estado_cierre
    manyToOne:
        idempleado:
            targetEntity: Empleado
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idEmpleado:
                    referencedColumnName: id
            orphanRemoval: false
        idSucursal:
            targetEntity: Empresa
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_sucursal:
                    referencedColumnName: id
            orphanRemoval: false
        idCliente:
            targetEntity: Cliente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_cliente:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
